### ISSUE TITLE
files are .py but supposed to be .pyc?

### ISSUE THREAD

**Issue by programprogrammer** [CJmusic/APCJ40_MKII#1]
I don't know anything about python but noticed that files in other folders are .pyc . I'm asking because the script is visible but isn't working in Ableton 11

**Comment by designerfuzzi** [comment]
`.pyc` are compiled python scripts, you can ignore them or erase them when there is a counter part `.py` so Ableton will recompile at next start.

**Comment by CJmusic** [comment]
What @designerfuzzi said. Ableton ships with complied .pyc but .py files work just fine. You can even place this .py in a Midi Remote Scripts folder in your User library and ableton should read it. The codes not working atm, it should compile now on the master branch at least.
